# Generated by Django 3.2.8 on 2021-11-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lowongan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_instansi', models.TextField(blank=True, null=True)),
                ('jenis_pekerjaan', models.TextField(max_length=200)),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('deskripsi', models.TextField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='business',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
